### ISSUE TITLE
attention visualization of different decoder layers 

### ISSUE THREAD

**Issue by SuperWu090** [facebookresearch/fairseq-lua#114]
Hi, 
I am trying to make attention visualization of different decoder layers right now. I have successfully visualize the top attention layer, as the search module offers the **attns** vector. 

However, I do not know how to  visualize all the other attention layers as the Appendix part C of the original Conv-attention paper. Would you please tell me how to deal with this problem ? @michaelauli @jgehring 

Thanks very much !

**Comment by Lelio-lliu** [comment]
I have met the same problem.

**Comment by jgehring** [comment]
Unfortunately, there is no option for this yet. By default, the FConv model provides an average of attention scores for all layers. For the paper, I simply modified the code of the [`generationAttention` callback]( https://github.com/facebookresearch/fairseq/blob/master/fairseq/models/fconv_model.lua#L700) to select a specific layer instead of looping over all of them.

**Comment by SuperWu090** [comment]
@jgehring It works quite well ! Thanks very much !
