### ISSUE TITLE
Epoch jumped from 20 to 100

### ISSUE THREAD

**Issue by ozancaglayan** [facebookresearch/fairseq-lua#26]
Hi,

My training jumped from epoch 20 to epoch 100 and stopped. The command launched for initiating the training was:
```
fairseq train -sourcelang tr -targetlang en -datadir ../data-bin/wmt17-tr-en \
  -model blstm -nembed 200 -noutembed 200 -nhid 500 -dropout 0.3 -dropout_hid 0 -optim adam -lr 0.0003125 \
  -savedir blstm -ngpus 1 -validbleu -log_interval 10 -batchsize 64
```

Here's the end of the log:

```
| epoch 019 | 0161656 updates | words/s   14482| trainloss     1.94 | train ppl     3.84
| epoch 019 | 0161666 updates | words/s   13245| trainloss     1.97 | train ppl     3.91
| epoch 019 | 0161676 updates | words/s   14300| trainloss     2.45 | train ppl     5.46
| checkpoint 020 | epoch 020 | 0161680 updates | s/checkpnt     632 | words/s   14126 | lr 0.000313
| checkpoint 020 | epoch 020 | 0161680 updates | trainloss     2.10 | train ppl     4.30
| checkpoint 020 | epoch 020 | 0161680 updates | validloss     4.36 | valid ppl    20.55 | testloss     4.40 | test ppl    21.16
| checkpoint 020 | epoch 020 | 0161680 updates | validbleu    17.67 | valid BP      0.90
| checkpoint 020 | epoch 020 | 0161680 updates | saved model to blstm/model_epoch20.th7
| epoch 100 | 0161680 updates | 0000000 epoch updates | path blstm/state_epoch100.th7
| epoch 100 | 0161680 updates | 0000000 epoch updates | path blstm/state_last.th7
| epoch 100 | 0161680 updates | 0000000 epoch updates | path blstm/state_last.th7
| Test with beam=1: BLEU4 = 19.06, 47.9/24.1/14.3/9.0 (BP=0.971, ratio=1.029, sys_len=85120, ref_len=87630)
| Test with beam=5: BLEU4 = 20.60, 51.5/27.1/16.5/10.5 (BP=0.929, ratio=1.074, sys_len=81595, ref_len=87630)
| Test with beam=10: BLEU4 = 20.91, 51.9/27.6/17.0/10.8 (BP=0.923, ratio=1.080, sys_len=81120, ref_len=87630)
| Test with beam=20: BLEU4 = 20.94, 52.0/27.7/17.1/10.9 (BP=0.919, ratio=1.084, sys_len=80841, ref_len=87630)
```

Another thing is that although I gave `-batchsize 64`, the # of updates that were done for completing an epoch was much larger than it should be: ~8000 vs. ~5000 (training set size: 348K samples)

**Comment by jgehring** [comment]
"epoch 100" is an artifact from logging. Training has finished (early stopping), so the epoch is set to max_epoch to stop training.

Regarding batch size: I assume you trained with multiple GPUs? The effective batch size will be `-bsz` times `-ngpus`.

**Comment by ozancaglayan** [comment]
Okay for the logging artifact but for batch size thing, I pass CUDA_VISIBLE_DEVICES=0 and -ngpus 1 to both blstm and fconv. fconv seems to respect my batch_size of 64 since an epoch completes at around 5300 updates but not the same thing for blstm.

Also just a side-note, the intermediate BLEU computations are substantially higher than expected when we use BPE tokenization. I think the evaluation with BLEU should be done on files with `@@`stitched.

Thanks!

**Comment by jgehring** [comment]
I see, so in this case the batch size differs due to bptt batching. The blstm example in README.md uses the default value for `-bptt`, which is 25. This will produce multiple mini-batches for sentences longer than 25 words.

Regarding validation BLEU: You're right, and this also applies to test BLEU. Currently, the code is totally oblivious to BPE as we consider it to be an external text pre- and post-processing step. In the same vein, code comments and program output avoid talking about "words" but rather mention "tokens". While this provides maximum flexibility, it comes with some inconveniences like default BLEU scores being off.

I think for maximum convenience, there could be a dedicated tokenizer function and Dictionary for BPE (e.g. with a custom `getString()` method that stitches sub-words together). I'd rather not hard-code a BPE delimiter for generation.

**Comment by ozancaglayan** [comment]
Thanks!
