### ISSUE TITLE
bleu calculate 

### ISSUE THREAD

**Issue by njuzrs** [facebookresearch/fairseq-lua#63]
we are doing some research about the network, we have a question that about BLEU score. Is the BLEU score of the test corpus just the average value about each sentence? or any other ways? Thanks for answering!

**Comment by michaelauli** [comment]
We compute corpus BLEU in the standard way, i.e., it is not an average of
sentence-level BLEU score as you suggest.

**Comment by njuzrs** [comment]
In our own work, we use the python package 'nltk.translate.bleu_score.corpus_bleu' to compute the corpus BLEU, I'M not sure whether our approach is comparable to  yours. could you please provide some references about 'the standard way' of  your computing corpus BLEU?

**Comment by michaelauli** [comment]
I am not familiar to the NLTK implementation but you can compare it to the
Moses perl script (
https://github.com/moses-smt/mosesdecoder/blob/617e8c8/scripts/generic/mteval-v13a.pl)
which gives the same result as our implementation.

**Comment by nikefd** [comment]
@njuzrs 
I think they are the same. 
You can see the detail in the file `fairseq\clib\bleu.lua` and `fairseq\clib\bleu.cpp`.
As for nltk, you can see the source code of corpus_bleu [here].(http://www.nltk.org/_modules/nltk/translate/bleu_score.html#corpus_bleu)
In the nltk 3.2.1, the default BLEU score uses n=4 which includes unigrams to 4 grams. If your sentence is smaller than 4, you need to reset the N value, otherwise ZeroDivisionError: Fraction(0, 0) error will be returned. 
In the nltk 3.2.4, the problem is solved. 
So I think if you use the nltk 3.2.4, they are the same.

**Comment by nikefd** [comment]
@michaelauli @njuzrs 
I am confused with the bleu too…
I am a new hand so I have a lot of question, haha. 

In the section evaluation of your paper [Convolutional Sequence to Sequence Learning](https://arxiv.org/abs/1705.03122),  you said
> Finally, we compute case-sensitive tokenized BLEU, except forWMT’16English-Romanian where we use detokenized BLEU to be comparable with Sennrich et al. (2016b)[4].

and the [4] is refer to https://github.com/moses-smt/mosesdecoder/blob/617e8c8/scripts/generic/{multi-bleu.perl,mteval-v13a.pl}
So I think your implementation is not all same as mteval-v13a.pl, **but I am not really sure.**

I think the nltk is the same with your implementation in the code, ** I am also not sure about it.**
I see the detail in the file fairseq\clib\bleu.lua and fairseq\clib\bleu.cpp, it calculate use 4-gram BLEU.
As for nltk, you can see the source code of corpus_bleu [here](http://www.nltk.org/_modules/nltk/translate/bleu_score.html#corpus_bleu), it also use 4-gram BLEU.
In the nltk 3.2.1, the default BLEU score uses n=4 which includes unigrams to 4 grams. If your sentence is smaller than 4, you need to reset the N value, otherwise ZeroDivisionError: Fraction(0, 0) error will be returned.
In the nltk 3.2.4, the problem is solved.
So I think if I use the nltk 3.2.4, they are the same.

Help me, please!
Thanks! Thanks! Thanks! : )

BTW, I think if you can add some timestamp in the log info, it will be more 👍.

**Comment by jgehring** [comment]
> So I think your implementation is not all same as mteval-v13a.pl, but I am not really sure.

We use mteval-v13a.pl to compute detokenized BLEU scores for English-Romanian. For tokenized BLEU scores, we use our own implementation which produces identical results than multi-bleu.perl, i.e. it counts n-gram matches up to and including length 4.

Re time-stamps in logs: yes, this sounds like a good thing to add. Internally, the logs are consumed by another program which adds these time-stamps so we didn't have a need to add them. PRs are welcome, though :)
