### ISSUE TITLE
What are the buffers, difference between prepareInput and prepareSource?

### ISSUE THREAD

**Issue by posenhuang** [facebookresearch/fairseq-lua#66]
1. When I look into the fairseq/models/*_model.lua, it is not clear to me what the buffers are and how the buffer is used. Can you give me some instructions, documentations for it? I want to add new models but I need to understand it more. 
2. What is the difference between source and input in https://github.com/facebookresearch/fairseq/blob/master/fairseq/models/avgpool_model.lua#L309 ?
It seems the source will correspond to the input of the make() function. 
3. Where is the criterion defined? Where should I change it for using different criterion?

Thanks a lot!

**Comment by jgehring** [comment]
Hi @posenhuang!

1.  Are you talking about the buffers dictionary in the prepare* functions? Their purpose is to avoid frequent creation of new tensors on the GPU. They are upvalues for the functions that are returned, i.e. they are bound to them and can be used in a similar way than globals (although they are only visible from the returned function)
2. "Source" refers to the source language input, "input" refers to the target language input (i.e. previous words). You should start reading from ~~`prepareInput()`~~ `prepareSample()` because this function prepares the actual model input (`sample.input`). `make()` returns an `nn.Module` which takes `sample.input` as input and tries to predict `sample.target`.
3. The criterion is defined in https://github.com/facebookresearch/fairseq/blob/master/train.lua#L203.

**Comment by posenhuang** [comment]
Thanks a lot! I'll read through it in more details with these contexts.

**Comment by posenhuang** [comment]
@jgehring, a follow up question, in 2., do you mean "prepareSample()" instead of "prepareInput()"?

**Comment by jgehring** [comment]
Yes, you're totally right :) I edited my answer above.

**Comment by posenhuang** [comment]
Thanks!
