### ISSUE TITLE
Zero shot

### ISSUE THREAD

**Issue by Bachstelze** [facebookresearch/fairseq-lua#7]
Is this architecture compatible with zero shot translation?
If yes: Are there plans to implement it?

**Comment by jgehring** [comment]
Are you referring to the work at https://arxiv.org/abs/1611.04558? It should be possible to do this since it requires a change in data pre-processing only, i.e. you'd have to build the BPE codes over multiple languages and, after encoding your training data, prefix each sentence with a target language marker. `fairseq preprocess` will pick up all of this afterwards.

Maybe it's worth checking out `makedict.lua` and `binarize.lua` for simple code that calls the dictionary building and text binarization functions in isolation. This might allow for simpler experimentation.
