### ISSUE TITLE
Checkpoints frequency

### ISSUE THREAD

**Issue by AwesomeLemon** [facebookresearch/fairseq-lua#71]
I couldn't find an option that specifies how often current model evaluation is conducted. (I'm interested in BLEU scores).
I supposed that option '-save_interval' should do it, but apparently it doesn't.
Could anyone please point me in the right direction?

**Comment by michaelauli** [comment]
Yes, you would have to change the code to do this. -save_interval just
specifies how often the model is serialized to disk.

**Comment by AwesomeLemon** [comment]
Hmmm, and could you tell where can I do that?
Also, I wonder what word 'epoch' means in this framework? I've alway thought that it means 'the model saw all samples 1 time', but if it's so, I can't understand why in my case the next epoch started after 69.000 iterations with batch size == 32 (meaning that model saw 69000 * 32 = 2 208 000 samples), and I have training dataset of 1 800 000 samples. The only explanation I see is that model keeps track of which samples it saw and since they're picked at random it takes more steps to see all samples. Is this the case?

**Comment by jgehring** [comment]
Regarding the difference between updates and samples: If you use `-maxbatch` or `-bptt`, a mini-batch may yield more than one sample for the model because the batch might be split into several smaller batches. Hence, the number of updates may differ from the number of sentences in your training set.

For more frequent checkpointing, you can try calling `onCheckpoint` (defined in [train.lua:318](https://github.com/facebookresearch/fairseq/blob/master/train.lua#L318)) in regular intervals from the `onUpdate` hook (see [a few lines below](https://github.com/facebookresearch/fairseq/blob/master/train.lua#L346)). Please let me know if you run into issues with this.

**Comment by AwesomeLemon** [comment]
Thanks for the information. You've answered my questions, so I'm closing the issue.
@jgehring if I try it and have any problems, I'll report them here.
