### ISSUE TITLE
preprocess  problem

### ISSUE THREAD

**Issue by linhanxiao** [facebookresearch/fairseq-lua#87]
in the function tokenizer.binarize ,
        if idx == dict.unk_index and word ~= dict.unk then 
            nunk = nunk + 1 
why  the nunk represented for the number of tokens replaced by <unk>，in the file 'Dictionary.lua',the 'dict.unk_index=1',so I couldn't understand it!

**Comment by michaelauli** [comment]
I am not quite sure what you mean, can you please be more specific?

**Comment by linhanxiao** [comment]
in the function tokenizer.binarize,
what  is the meaning of the nunk variable

**Comment by michaelauli** [comment]
The number of tokens that were mapped to the unknown token.

**Comment by linhanxiao** [comment]
i get it,buti n the function tokenizer.binarize i can not understand the condition--idx == dict.unk_index and word ~= dict.unk

**Comment by linhanxiao** [comment]
why nunk = nunk + 1 when idx == dict.unk_index and word ~= dict.unk

**Comment by linhanxiao** [comment]
in the Dictionary.lua ,I can not find the code that map the tokens to the unknown tokens

**Comment by nikefd** [comment]
hi, hanxiao @linhanxiao , 
In the file `Dictionary.lua`, you can find that 
```
function Dictionary:getIndex(symbol)
    local idx = self.symbol_to_index[symbol]
    if idx and idx <= self.cutoff then
        return idx
    end
    return self.unk_index
end
```
So if the word isn't in the dict or its id bigger than the size of dict. `dict:getIndex(word)` will return dict.unk_index. If the word is '\<unk\>' the index will return dict.unk_index, but it isn't a unk, so we should add a condition that `word ~= dict.unk`.
So when `idx == dict.unk_index and word ~= dict.unk` , the word is an unk, so `nunk = nunk + 1`. 

I hope it is helpful to you.

**Comment by neuraltalk** [comment]
nikefd is correct.

Additionally, in Dictionary, this [line](https://github.com/facebookresearch/fairseq/blob/af637990abffde688b975ccd124ac2c525f83257/fairseq/text/Dictionary.lua#L98) should be changed as below.

>   if self.threshold > 1 then

When you guys want to set the threshold to 1.
In Dictionary, finalize() cuts offs the size of dictionary by the defined threshold.
But in _applyFrequencyThreshold(), the initial value of cutoff is assigned to math.huge, and only frequencies smaller than threshold in for loop are taken to set the new cutoff.
But all the vocabularies are greater than 1, so the for loop does nothing, and finally just returns nspecial(3) since cutoff has the inital value, math.huge.

**Comment by linhanxiao** [comment]
thanks for your answer
